name: Server CD

on:
  push:
    branches: ["main"]
    paths:
      - "apps/server/**"
      - ".github/workflows/server.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "apps/server/**"
      - ".github/workflows/server.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add server remote origin
        run: git remote add heroku-backend https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_SERVER_APP_NAME }}.git
      - name: Deploy server to Heroku
        run: git push heroku-server `git subtree split --prefix apps/server master`:refs/heads/master --force
